In [11]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# conv

In [12]:
x_input = torch.randn(1, 3, 5, 5)

In [13]:
x_input

tensor([[[[ 0.3988, -0.4025, -1.1852, -0.7634,  0.9461],
          [ 0.3797,  1.3963, -0.0879,  0.7834, -1.1772],
          [-1.7358,  0.4994,  0.2362,  0.8510, -0.9512],
          [-1.1865, -1.8903,  0.2350,  1.0328, -0.5224],
          [-2.8142,  0.3626, -0.7659,  0.0217, -0.8809]],

         [[-0.0359,  0.2904, -0.2523, -1.5075, -0.5286],
          [-0.6653, -0.9982,  0.3480, -0.4155, -1.0053],
          [-0.2476, -0.3937, -0.2234,  0.8376,  1.7656],
          [ 2.6439, -1.4252, -0.3018,  2.5700,  1.0315],
          [ 0.3061,  1.2099, -1.6662,  1.2169,  0.4643]],

         [[ 0.5061, -0.2757,  0.1606,  0.4163,  1.0276],
          [-0.0895, -0.0849,  0.0183, -0.1733,  0.1452],
          [-1.2364,  1.0093, -0.1869, -1.3623,  1.6553],
          [-2.7025,  0.4528,  0.7977,  0.6065,  0.5799],
          [ 0.9179,  1.6105, -0.5210,  0.6025,  1.4335]]]])

In [14]:
conv1 = nn.Conv2d(3, 2, kernel_size=3, stride=1, padding=1)
out1 = conv1(x_input)

In [15]:
out1

tensor([[[[-0.1413, -0.1308, -0.1939, -0.0320, -0.0710],
          [ 0.0247,  0.0136,  0.4340,  0.1109, -0.0246],
          [ 1.3168,  0.1551, -0.2029,  0.5856,  0.6564],
          [ 0.6092, -0.5818,  0.0931, -0.1379,  0.5082],
          [ 0.5218, -0.2507, -0.9184,  0.8619,  0.2839]],

         [[ 0.5699,  0.0931,  0.1311, -0.0082,  0.0926],
          [ 0.2599,  0.1711,  0.4746, -0.5866,  0.0822],
          [-0.3984, -0.0579, -0.6498, -0.2204,  0.0923],
          [ 0.1281,  1.0687, -0.1081, -1.2353,  1.1979],
          [ 0.3156,  0.3095,  0.7972, -0.4272,  0.2110]]]],
       grad_fn=<ThnnConv2DBackward>)

In [16]:
out1.shape

torch.Size([1, 2, 5, 5])

In [17]:
conv2 = nn.Conv2d(3, 2, kernel_size=3, stride=1, padding=0)
out2 = conv2(x_input)
print(out2.shape)

torch.Size([1, 2, 3, 3])


In [18]:
conv3 = nn.Conv2d(3, 2, kernel_size=3, stride=1, padding=2)
out3 = conv3(x_input)
print(out3.shape)

torch.Size([1, 2, 7, 7])


In [19]:
conv4 = nn.Conv2d(3, 2, kernel_size=(3, 5), stride=1, padding=0)
out4 = conv4(x_input)
print(out4.shape)

torch.Size([1, 2, 3, 1])


In [20]:
conv4.weight.shape

torch.Size([2, 3, 3, 5])

In [21]:
conv4.weight

Parameter containing:
tensor([[[[-0.0630, -0.0752,  0.0765, -0.1275,  0.1374],
          [ 0.1024,  0.0123,  0.1084, -0.0734, -0.1359],
          [-0.0706, -0.1024, -0.0767, -0.1442, -0.0427]],

         [[-0.0023,  0.0238,  0.0775,  0.0384,  0.0161],
          [-0.0254, -0.0588, -0.0819,  0.0958,  0.0590],
          [ 0.1059, -0.0544, -0.0340, -0.0647, -0.1224]],

         [[-0.1182,  0.1317, -0.0232, -0.0651,  0.1388],
          [-0.0132, -0.1476, -0.1401,  0.0719,  0.0008],
          [ 0.1446, -0.0059,  0.0172,  0.1353,  0.1313]]],


        [[[-0.0133, -0.1243,  0.0743,  0.0955, -0.0378],
          [-0.0143,  0.0048, -0.1073,  0.0379, -0.1279],
          [-0.1283,  0.0504, -0.0302,  0.0212,  0.0287]],

         [[-0.0497,  0.1258,  0.1230,  0.0954, -0.0656],
          [ 0.0563, -0.0153, -0.0414, -0.0362, -0.1265],
          [ 0.0097, -0.0129, -0.1101,  0.1003, -0.1287]],

         [[ 0.0964, -0.1401, -0.0152,  0.0834, -0.1031],
          [-0.1384, -0.0127,  0.1317,  0.0477,  0.0471

stride don't change the shape

In [55]:
conv5 = nn.Conv2d(3, 2, kernel_size=3, stride=2, padding=1)
out1 = conv5(x_input)
print(out1.shape)

torch.Size([1, 2, 3, 3])


In [56]:
print(x_input)
print(conv5.weight)
print(out1)

tensor([[[[ 0.3988, -0.4025, -1.1852, -0.7634,  0.9461],
          [ 0.3797,  1.3963, -0.0879,  0.7834, -1.1772],
          [-1.7358,  0.4994,  0.2362,  0.8510, -0.9512],
          [-1.1865, -1.8903,  0.2350,  1.0328, -0.5224],
          [-2.8142,  0.3626, -0.7659,  0.0217, -0.8809]],

         [[-0.0359,  0.2904, -0.2523, -1.5075, -0.5286],
          [-0.6653, -0.9982,  0.3480, -0.4155, -1.0053],
          [-0.2476, -0.3937, -0.2234,  0.8376,  1.7656],
          [ 2.6439, -1.4252, -0.3018,  2.5700,  1.0315],
          [ 0.3061,  1.2099, -1.6662,  1.2169,  0.4643]],

         [[ 0.5061, -0.2757,  0.1606,  0.4163,  1.0276],
          [-0.0895, -0.0849,  0.0183, -0.1733,  0.1452],
          [-1.2364,  1.0093, -0.1869, -1.3623,  1.6553],
          [-2.7025,  0.4528,  0.7977,  0.6065,  0.5799],
          [ 0.9179,  1.6105, -0.5210,  0.6025,  1.4335]]]])
Parameter containing:
tensor([[[[ 0.1768, -0.1504,  0.0241],
          [-0.1194,  0.1225, -0.0014],
          [ 0.0787, -0.0429, -0.0905]]

In [57]:
little_input = torch.randn(1, 2, 5, 5)

In [58]:
conv_little = nn.Conv2d(2, 1, 3, 2, 1)
for name, param in conv_little.named_parameters():
    print(name, param)

weight Parameter containing:
tensor([[[[ 0.2288, -0.0035, -0.1241],
          [ 0.0196,  0.1826,  0.0504],
          [ 0.0047, -0.0265,  0.2012]],

         [[ 0.1371, -0.0183,  0.0400],
          [ 0.2178,  0.0037,  0.0624],
          [ 0.0871, -0.0436, -0.1031]]]], requires_grad=True)
bias Parameter containing:
tensor([0.0881], requires_grad=True)


In [59]:
nn.init.constant_(conv_little.weight, 1)
nn.init.constant_(conv_little.bias, 0)
for name, param in conv_little.named_parameters():
    print(name, param)

weight Parameter containing:
tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]], requires_grad=True)
bias Parameter containing:
tensor([0.], requires_grad=True)


In [60]:
little_output = conv_little(little_input)

In [61]:
print(little_input)
print(little_output)

tensor([[[[ 0.7482, -1.1624,  0.2837,  1.7902, -0.2119],
          [-0.1691,  0.3309,  0.3589,  0.7203, -0.2935],
          [-0.6516,  0.2635,  0.2766,  1.9820,  0.1616],
          [ 0.0415, -0.8589,  0.0520, -0.6278,  0.2777],
          [ 1.7040, -1.7370,  0.1391,  1.3080, -1.6037]],

         [[ 1.8383,  0.2615,  0.4886, -0.7360, -0.3543],
          [ 0.6207, -0.6951,  1.2016, -0.9090,  1.7623],
          [-0.0618,  1.0915,  0.0502, -0.6160,  0.2235],
          [-1.6294,  0.3055,  1.5726, -0.1869, -1.1324],
          [ 0.8465,  1.7157,  0.1072,  0.3534, -0.4433]]]])
tensor([[[[ 1.7728,  1.9331,  1.7681],
          [-1.4123,  4.3119,  1.3618],
          [ 0.3879,  2.1430, -2.0550]]]], grad_fn=<ThnnConv2DBackward>)


# Pooling

In [27]:
maxpool1 = nn.MaxPool2d(2, 1, 0)
out11 = maxpool1(x_input)
print(x_input)
print(out11.shape)

print(out11)

tensor([[[[ 0.3988, -0.4025, -1.1852, -0.7634,  0.9461],
          [ 0.3797,  1.3963, -0.0879,  0.7834, -1.1772],
          [-1.7358,  0.4994,  0.2362,  0.8510, -0.9512],
          [-1.1865, -1.8903,  0.2350,  1.0328, -0.5224],
          [-2.8142,  0.3626, -0.7659,  0.0217, -0.8809]],

         [[-0.0359,  0.2904, -0.2523, -1.5075, -0.5286],
          [-0.6653, -0.9982,  0.3480, -0.4155, -1.0053],
          [-0.2476, -0.3937, -0.2234,  0.8376,  1.7656],
          [ 2.6439, -1.4252, -0.3018,  2.5700,  1.0315],
          [ 0.3061,  1.2099, -1.6662,  1.2169,  0.4643]],

         [[ 0.5061, -0.2757,  0.1606,  0.4163,  1.0276],
          [-0.0895, -0.0849,  0.0183, -0.1733,  0.1452],
          [-1.2364,  1.0093, -0.1869, -1.3623,  1.6553],
          [-2.7025,  0.4528,  0.7977,  0.6065,  0.5799],
          [ 0.9179,  1.6105, -0.5210,  0.6025,  1.4335]]]])
torch.Size([1, 3, 4, 4])
tensor([[[[ 1.3963,  1.3963,  0.7834,  0.9461],
          [ 1.3963,  1.3963,  0.8510,  0.8510],
          [ 0.499

In [28]:
maxpool2 = nn.MaxPool2d(2, 1, 1)
out11 = maxpool2(x_input)
print(x_input)
print(out11.shape)
print(out11)

tensor([[[[ 0.3988, -0.4025, -1.1852, -0.7634,  0.9461],
          [ 0.3797,  1.3963, -0.0879,  0.7834, -1.1772],
          [-1.7358,  0.4994,  0.2362,  0.8510, -0.9512],
          [-1.1865, -1.8903,  0.2350,  1.0328, -0.5224],
          [-2.8142,  0.3626, -0.7659,  0.0217, -0.8809]],

         [[-0.0359,  0.2904, -0.2523, -1.5075, -0.5286],
          [-0.6653, -0.9982,  0.3480, -0.4155, -1.0053],
          [-0.2476, -0.3937, -0.2234,  0.8376,  1.7656],
          [ 2.6439, -1.4252, -0.3018,  2.5700,  1.0315],
          [ 0.3061,  1.2099, -1.6662,  1.2169,  0.4643]],

         [[ 0.5061, -0.2757,  0.1606,  0.4163,  1.0276],
          [-0.0895, -0.0849,  0.0183, -0.1733,  0.1452],
          [-1.2364,  1.0093, -0.1869, -1.3623,  1.6553],
          [-2.7025,  0.4528,  0.7977,  0.6065,  0.5799],
          [ 0.9179,  1.6105, -0.5210,  0.6025,  1.4335]]]])
torch.Size([1, 3, 6, 6])
tensor([[[[ 0.3988,  0.3988, -0.4025, -0.7634,  0.9461,  0.9461],
          [ 0.3988,  1.3963,  1.3963,  0.7834, 

In [29]:
maxpool2 = nn.MaxPool2d(2, 2, 0)
out11 = maxpool2(x_input)
print(out11.shape)
print(out11)

torch.Size([1, 3, 2, 2])
tensor([[[[1.3963, 0.7834],
          [0.4994, 1.0328]],

         [[0.2904, 0.3480],
          [2.6439, 2.5700]],

         [[0.5061, 0.4163],
          [1.0093, 0.7977]]]])
