In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
x_input = torch.randn(1, 3, 5, 5)

In [3]:
x_input

tensor([[[[ 0.2576, -0.0099,  0.2829, -0.1702, -0.5715],
          [ 0.7104, -1.3992, -0.3415,  0.1275,  0.5706],
          [-1.9449,  0.4265, -0.5839, -1.9471, -2.1250],
          [ 0.1576, -0.7712, -1.0656, -0.3378, -0.8650],
          [ 0.7309, -1.5064,  1.3109,  1.5246,  0.6502]],

         [[-1.4453,  0.2089,  0.2586, -0.6369,  0.4095],
          [ 1.3268, -0.6307, -0.9608, -0.0261,  0.6277],
          [-2.0889, -0.5692,  1.1346, -2.1920, -2.0180],
          [ 0.3122,  0.0811, -1.6238, -1.0427,  0.2064],
          [-0.1784,  0.2840, -2.3459,  1.8085,  1.7743]],

         [[-0.7225,  0.5364,  0.3067, -0.1189,  0.7855],
          [ 0.9150, -0.4012,  0.0843, -1.2318, -1.2012],
          [ 1.4811, -0.3819,  1.2347,  1.2065, -1.0288],
          [-1.4630,  0.5192,  0.2413,  1.2295,  0.8132],
          [-0.2677,  0.9457, -0.4371, -0.2998,  1.7715]]]])

In [5]:
conv1 = nn.Conv2d(3, 2, kernel_size=3, stride=1)
out1 = conv1(x_input)

In [6]:
out1

tensor([[[[ 0.7134, -0.8244,  0.0189],
          [-0.8252,  0.7469,  0.1264],
          [ 0.3399,  0.7703, -1.1446]],

         [[-0.3618,  0.5327, -0.1660],
          [ 0.5665,  0.2026,  0.0491],
          [-0.2238, -0.9973,  1.1545]]]], grad_fn=<ThnnConv2DBackward>)

In [7]:
out1.shape

torch.Size([1, 2, 3, 3])

In [8]:
conv2 = nn.Conv2d(3, 2, kernel_size=3, stride=1, padding=0)
out2 = conv2(x_input)
print(out2.shape)

torch.Size([1, 2, 3, 3])


In [10]:
conv3 = nn.Conv2d(3, 2, kernel_size=3, stride=1, padding=2)
out3 = conv3(x_input)
print(out3.shape)

torch.Size([1, 2, 7, 7])


In [11]:
conv4 = nn.Conv2d(3, 2, kernel_size=(3, 5), stride=1, padding=0)
out4 = conv4(x_input)
print(out4.shape)

torch.Size([1, 2, 3, 1])


In [14]:
conv4.weight.shape

torch.Size([2, 3, 3, 5])

In [15]:
conv4.weight

Parameter containing:
tensor([[[[-0.1098, -0.0818, -0.0383,  0.0322,  0.0717],
          [ 0.1388, -0.0503,  0.0726, -0.0727, -0.0446],
          [ 0.0151, -0.1412,  0.1189,  0.1017,  0.0640]],

         [[ 0.1345,  0.0229,  0.0581,  0.0161, -0.0574],
          [-0.1017, -0.0644, -0.1049, -0.0604, -0.1365],
          [-0.0603, -0.0059,  0.1282, -0.1398,  0.0388]],

         [[ 0.1436, -0.0334, -0.0931, -0.1281, -0.1086],
          [-0.1231,  0.1157, -0.0891, -0.0066,  0.0215],
          [ 0.0597,  0.1322, -0.0765,  0.1385, -0.1426]]],


        [[[-0.0313,  0.1148,  0.1438, -0.1159, -0.0506],
          [ 0.1118, -0.1334,  0.0250, -0.0792,  0.1395],
          [-0.0481,  0.0142,  0.0527, -0.0460, -0.1294]],

         [[-0.0042,  0.0351, -0.0371,  0.0960,  0.0043],
          [ 0.0446,  0.0953,  0.1166,  0.0683,  0.0608],
          [-0.0413, -0.0933,  0.0481, -0.0724,  0.0054]],

         [[-0.1095,  0.0633,  0.0247,  0.1185, -0.1050],
          [ 0.0422,  0.1094, -0.1409, -0.0071, -0.0384

In [16]:
out1

tensor([[[[ 0.7134, -0.8244,  0.0189],
          [-0.8252,  0.7469,  0.1264],
          [ 0.3399,  0.7703, -1.1446]],

         [[-0.3618,  0.5327, -0.1660],
          [ 0.5665,  0.2026,  0.0491],
          [-0.2238, -0.9973,  1.1545]]]], grad_fn=<ThnnConv2DBackward>)

In [17]:
maxpool1 = nn.MaxPool2d(2, 1)

In [18]:
out11 = maxpool1(out1)

In [19]:
out11

tensor([[[[0.7469, 0.7469],
          [0.7703, 0.7703]],

         [[0.5665, 0.5327],
          [0.5665, 1.1545]]]], grad_fn=<MaxPool2DWithIndicesBackward>)