In [1]:
import torch

## order of a tensor

* the order of a tensor is according to the dim order

In [4]:
b = torch.randn(2, 1, 3)

In [5]:
b

tensor([[[ 0.9343,  0.1079,  0.0822]],

        [[ 0.0849, -0.4805, -0.2615]]])

## view

* reshape the tensor according to the order

In [6]:
b.view(2, -1)

tensor([[ 0.9343,  0.1079,  0.0822],
        [ 0.0849, -0.4805, -0.2615]])

In [7]:
b.view(-1, 3)

tensor([[ 0.9343,  0.1079,  0.0822],
        [ 0.0849, -0.4805, -0.2615]])

In [8]:
b.view(1, -1)

tensor([[ 0.9343,  0.1079,  0.0822,  0.0849, -0.4805, -0.2615]])

## squeeze and unsqueeze

* appedn or reduce the dim

In [10]:
a = torch.randn(4, 1, 28, 28)

In [11]:
a.unsqueeze(0).shape

torch.Size([1, 4, 1, 28, 28])

In [12]:
a.unsqueeze(1).shape

torch.Size([4, 1, 1, 28, 28])

In [13]:
a = torch.randn(1, 1, 32, 1)

In [14]:
a.squeeze().shape

torch.Size([32])

In [15]:
a.squeeze(0).shape

torch.Size([1, 32, 1])

## permute and transpose

* change the dim order

* the same efficient

In [16]:
a = torch.rand(3,2,4)

In [17]:
a

tensor([[[0.4987, 0.6590, 0.1445, 0.3324],
         [0.2064, 0.2913, 0.6959, 0.3245]],

        [[0.5296, 0.4775, 0.0038, 0.9545],
         [0.5742, 0.8229, 0.1320, 0.5391]],

        [[0.0303, 0.9823, 0.2841, 0.6818],
         [0.1404, 0.9056, 0.2583, 0.2237]]])

In [18]:
a.permute(2, 1, 0)

tensor([[[0.4987, 0.5296, 0.0303],
         [0.2064, 0.5742, 0.1404]],

        [[0.6590, 0.4775, 0.9823],
         [0.2913, 0.8229, 0.9056]],

        [[0.1445, 0.0038, 0.2841],
         [0.6959, 0.1320, 0.2583]],

        [[0.3324, 0.9545, 0.6818],
         [0.3245, 0.5391, 0.2237]]])

In [19]:
a.permute(2, 1, 0).shape

torch.Size([4, 2, 3])

In [20]:
a.transpose(0, 2)

tensor([[[0.4987, 0.5296, 0.0303],
         [0.2064, 0.5742, 0.1404]],

        [[0.6590, 0.4775, 0.9823],
         [0.2913, 0.8229, 0.9056]],

        [[0.1445, 0.0038, 0.2841],
         [0.6959, 0.1320, 0.2583]],

        [[0.3324, 0.9545, 0.6818],
         [0.3245, 0.5391, 0.2237]]])

## cat

In [21]:
a = torch.randn(1, 3)

In [22]:
b = torch.randn(1, 3)
print(a)
print(b)

tensor([[ 1.1253, -0.0667, -0.1909]])
tensor([[-1.2261, -0.3433,  0.9019]])


In [23]:
c = torch.cat([a, b])

In [24]:
c

tensor([[ 1.1253, -0.0667, -0.1909],
        [-1.2261, -0.3433,  0.9019]])