In [1]:
## cross entropy

In [2]:
import torch
import torch.nn as nn

In [3]:
sigmoid = nn.Sigmoid()
softmax = nn.Softmax(dim=1)  # dim=1: sum of rows is one; dim=0: sum of columns is one

inputs = torch.randn(3, 2)

In [4]:
print(inputs)
print(sigmoid(inputs))
print(softmax(inputs))

tensor([[-1.6268,  0.4628],
        [ 0.0956, -0.5239],
        [-0.8535, -1.2983]])
tensor([[0.1643, 0.6137],
        [0.5239, 0.3719],
        [0.2987, 0.2144]])
tensor([[0.1101, 0.8899],
        [0.6501, 0.3499],
        [0.6094, 0.3906]])


In [5]:
label1 = torch.Tensor([[0, 1], [1, 0], [1, 0]])
label2 = torch.tensor([1, 0, 0], dtype=torch.int64)

In [6]:
BCELoss = nn.BCELoss()
BCEWithLogitsLoss = nn.BCEWithLogitsLoss()
CELoss = nn.CrossEntropyLoss()

In [7]:
print(BCELoss(sigmoid(inputs), label1))
print(BCEWithLogitsLoss(inputs, label1))
print(BCELoss(softmax(inputs), label1))
print(CELoss(inputs, label2))

tensor(0.5382)
tensor(0.5382)
tensor(0.3475)
tensor(0.3475)


In [8]:
inputs2 = sigmoid(inputs)[:, 1]

In [18]:
inputs2 = torch.FloatTensor(inputs2)
label2 = torch.tensor(label2, dtype=torch.float32)

F:\codingtools\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  


In [19]:
print(inputs2.dtype, label2.dtype)
print(BCELoss(inputs2, label2))

torch.float32 torch.float32
tensor(0.3983)
