In [1]:
## cross entropy

In [1]:
import torch
import torch.nn as nn

In [2]:
sigmoid = nn.Sigmoid()
softmax = nn.Softmax(dim=1)  # dim=1: sum of rows is one; dim=0: sum of columns is one

inputs = torch.randn(3, 2)

In [3]:
print(inputs)
print(sigmoid(inputs))
print(softmax(inputs))

tensor([[-1.3421, -2.0072],
        [ 0.1417,  0.2043],
        [-0.5273, -0.4909]])
tensor([[0.2072, 0.1185],
        [0.5354, 0.5509],
        [0.3712, 0.3797]])
tensor([[0.6604, 0.3396],
        [0.4843, 0.5157],
        [0.4909, 0.5091]])


In [4]:
label1 = torch.Tensor([[0, 1], [1, 0], [1, 0]])
label2 = torch.tensor([1, 0, 0], dtype=torch.int64)

In [5]:
BCELoss = nn.BCELoss()
BCEWithLogitsLoss = nn.BCEWithLogitsLoss()
CELoss = nn.CrossEntropyLoss()

In [6]:
print(BCELoss(sigmoid(inputs), label1))
print(BCEWithLogitsLoss(inputs, label1))
print(BCELoss(softmax(inputs), label1))
print(CELoss(inputs, label2))

tensor(0.8766)
tensor(0.8766)
tensor(0.8388)
tensor(0.8388)


In [10]:
inputs2 = inputs[:, 1]
print(inputs2)

tensor([-2.0072,  0.2043, -0.4909])


In [11]:
inputs2 = sigmoid(inputs2)
print(inputs2)

tensor([0.1185, 0.5509, 0.3797])


In [12]:
label2 = label2.float()

In [13]:
print(inputs2.dtype, label2.dtype)
print(BCELoss(inputs2, label2))

torch.float32 torch.float32
tensor(1.1371)
