In [1]:
## cross entropy

In [3]:
import torch
import torch.nn as nn

In [16]:
sigmoid = nn.Sigmoid()
softmax = nn.Softmax(dim=1)  # dim=1: sum of rows is one; dim=0: sum of columns is one

inputs = torch.randn(3, 2)

In [17]:
print(inputs)
print(sigmoid(inputs))
print(softmax(inputs))

tensor([[ 0.0178,  0.8244],
        [ 1.2344, -0.7891],
        [ 0.5391, -0.0204]])
tensor([[0.5045, 0.6952],
        [0.7746, 0.3124],
        [0.6316, 0.4949]])
tensor([[0.3086, 0.6914],
        [0.8832, 0.1168],
        [0.6363, 0.3637]])


In [26]:
label1 = torch.Tensor([[0, 1], [1, 0], [1, 0]])
label2 = torch.tensor([1, 0, 0], dtype=torch.int64)

In [20]:
BCELoss = nn.BCELoss()
BCEWithLogitsLoss = nn.BCEWithLogitsLoss()
CELoss = nn.CrossEntropyLoss()

In [27]:
print(BCELoss(sigmoid(inputs), label1))
print(BCEWithLogitsLoss(inputs, label1))
print(BCELoss(softmax(inputs), label1))
print(CELoss(inputs, label2))

tensor(0.4730)
tensor(0.4730)
tensor(0.3151)
tensor(0.3151)
